# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Tropy
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tropy is free open-source software that allows you to organize and describe
  photographs of research material.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tropy.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tropy
github_username: tropy

# Stripe test credentials
stripe_dev: pk_test_51JT0o3IfQcuZiDTgYUM3KIDT69YA5BL6kZMNDBrwLCLuVkGhFspqbynjnRgPqJgNy7A3bPd3or0AZIy9E0VkIChK00FGZh4e83
paymentEndpoint_dev: https://qlrmb89byi.execute-api.us-east-1.amazonaws.com/dev/
# paymentEndpoint_dev: http://127.0.0.1:3000/

# Stripe live credentials
stripe: pk_live_51JT0o3IfQcuZiDTgkKraHa2dBIaSF3BXW0WJPrOgA2PlvssbadO8rUCwOW6QzC1DrME6cPtwjkEE99PFuFx3KWJ700l2687cir
paymentEndpoint: https://cakatr39t1.execute-api.us-east-1.amazonaws.com/Prod/

# Options
show_excerpts: true

# Metadata for Jekyll SEO tag
tagline: Explore your research photos
twitter:
  username: tropy
  card: summary
#logo:
social:
  name: Tropy
  links:
    - https://twitter.com/tropy
    - https://github.com/tropy
google_site_verification: f4Qn7nonE_x2wrByaZVZfPeuP5iVt-W67eiIGE-KOWI
lang: en_US

# Set default twitter image and blog post classes via front matter defaults
page_image: &page_image "/assets/images/twitter-icon-1.1.png"

defaults:
  - scope:
      path: ""
    values:
      image: *page_image
  - scope:
      path: ""
      type: "posts"
    values:
      class: "blog blog-post"
      layout: "post"

# Set blog post permalinks
collections:
  posts:
    permalink: /blog/:slug

# Change the default sass_dir from _sass to assets/stylesheets
sass:
  sass_dir: assets/stylesheets

# RSS feed options
feed:
  path: /blog/rss/index.xml

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Serve command options
host: 0.0.0.0
